CREATE TYPE "public"."leave_event_action" AS ENUM('submitted', 'approved', 'declined', 'cancelled');--> statement-breakpoint
CREATE TABLE "leave_request_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"leave_request_id" uuid NOT NULL,
	"request_version" integer NOT NULL,
	"action" "leave_event_action" NOT NULL,
	"actor_profile_id" uuid NOT NULL,
	"actor_role" varchar(30) NOT NULL,
	"organization_timezone" varchar(100) NOT NULL,
	"was_late" boolean DEFAULT false NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"prior_status" "leave_status",
	"resulting_status" "leave_status" NOT NULL,
	"decision_note" varchar(500),
	"fallback_reason" varchar(500),
	CONSTRAINT "leave_request_events_note_length_check" CHECK ("leave_request_events"."decision_note" IS NULL OR char_length("leave_request_events"."decision_note") BETWEEN 1 AND 500),
	CONSTRAINT "leave_request_events_fallback_length_check" CHECK ("leave_request_events"."fallback_reason" IS NULL OR char_length("leave_request_events"."fallback_reason") BETWEEN 1 AND 500)
);
--> statement-breakpoint
DROP INDEX "leave_requests_employee_idx";--> statement-breakpoint
ALTER TABLE "leave_requests" ADD COLUMN "organization_id" uuid;--> statement-breakpoint
UPDATE "leave_requests" request SET "organization_id" = employee."organization_id" FROM "employees" employee WHERE employee."id" = request."employee_id" AND request."organization_id" IS NULL;--> statement-breakpoint
DO $$
DECLARE
  issue_count integer;
BEGIN
  SELECT count(*) INTO issue_count FROM leave_requests request LEFT JOIN employees employee ON employee.id = request.employee_id WHERE employee.id IS NULL OR request.organization_id IS NULL OR request.organization_id <> employee.organization_id;
  IF issue_count > 0 THEN RAISE EXCEPTION 'TIME_OFF_MIGRATION_ORPHAN_OR_ORGANIZATION_MISMATCH: % rows', issue_count; END IF;
  SELECT count(*) INTO issue_count FROM leave_requests WHERE end_date < start_date OR char_length(COALESCE(reason, '')) > 500;
  IF issue_count > 0 THEN RAISE EXCEPTION 'TIME_OFF_MIGRATION_INVALID_RANGE_OR_REASON: % rows', issue_count; END IF;
  SELECT count(*) INTO issue_count FROM leave_requests WHERE status <> 'draft';
  IF issue_count > 0 THEN RAISE EXCEPTION 'TIME_OFF_MIGRATION_UNEXPECTED_VISIBLE_STATE: % rows', issue_count; END IF;
  SELECT count(*) INTO issue_count FROM leave_requests first_request JOIN leave_requests second_request ON second_request.id > first_request.id AND second_request.employee_id = first_request.employee_id AND second_request.status IN ('submitted', 'approved') AND first_request.status IN ('submitted', 'approved') AND daterange(first_request.start_date, first_request.end_date, '[]') && daterange(second_request.start_date, second_request.end_date, '[]');
  IF issue_count > 0 THEN RAISE EXCEPTION 'TIME_OFF_MIGRATION_ACTIVE_OVERLAP: % pairs', issue_count; END IF;
END $$;--> statement-breakpoint
ALTER TABLE "leave_requests" ALTER COLUMN "organization_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "leave_requests" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "leave_request_events" ADD CONSTRAINT "leave_request_events_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leave_request_events" ADD CONSTRAINT "leave_request_events_leave_request_id_leave_requests_id_fk" FOREIGN KEY ("leave_request_id") REFERENCES "public"."leave_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "leave_request_events" ADD CONSTRAINT "leave_request_events_actor_profile_id_profiles_id_fk" FOREIGN KEY ("actor_profile_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "leave_request_events_request_version_unique" ON "leave_request_events" USING btree ("leave_request_id","request_version");--> statement-breakpoint
CREATE INDEX "leave_request_events_organization_order_idx" ON "leave_request_events" USING btree ("organization_id","occurred_at","id");--> statement-breakpoint
ALTER TABLE "leave_requests" ADD CONSTRAINT "leave_requests_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "leave_requests_id_organization_unique" ON "leave_requests" USING btree ("id","organization_id");--> statement-breakpoint
CREATE INDEX "leave_requests_organization_submitted_idx" ON "leave_requests" USING btree ("organization_id","submitted_at","id");--> statement-breakpoint
CREATE INDEX "leave_requests_employee_submitted_idx" ON "leave_requests" USING btree ("employee_id","submitted_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "leave_requests" ADD CONSTRAINT "leave_requests_version_positive" CHECK ("leave_requests"."version" > 0);--> statement-breakpoint
ALTER TABLE "leave_requests" ADD CONSTRAINT "leave_requests_reason_length_check" CHECK ("leave_requests"."reason" IS NULL OR char_length("leave_requests"."reason") <= 500);
--> statement-breakpoint
CREATE OR REPLACE FUNCTION current_time_off_profile(target_organization_id uuid) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT profile.id FROM profiles profile JOIN memberships membership ON membership.profile_id = profile.id WHERE profile.auth_user_id = auth.uid() AND profile.status = 'active' AND membership.organization_id = target_organization_id AND membership.status = 'active' LIMIT 1 $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION submit_leave_request(target_organization_id uuid, start_date date, end_date date, leave_type leave_type, reason text, retry_request_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE actor uuid; employee employees%ROWTYPE; request leave_requests%ROWTYPE; now_at timestamptz := transaction_timestamp(); BEGIN actor := current_time_off_profile(target_organization_id); IF actor IS NULL THEN RAISE EXCEPTION 'TIME_OFF_FORBIDDEN'; END IF; SELECT * INTO employee FROM employees WHERE organization_id = target_organization_id AND profile_id = actor FOR UPDATE; IF employee.id IS NULL OR employee.status <> 'active' THEN RAISE EXCEPTION 'TIME_OFF_FORBIDDEN'; END IF; IF start_date < (now_at AT TIME ZONE (SELECT timezone FROM organizations WHERE id = target_organization_id))::date OR end_date < start_date OR end_date - start_date + 1 > 366 THEN RAISE EXCEPTION 'TIME_OFF_INVALID_DATE_RANGE'; END IF; IF start_date < employee.hire_date OR (employee.termination_date IS NOT NULL AND end_date >= employee.termination_date) THEN RAISE EXCEPTION 'TIME_OFF_OUTSIDE_EMPLOYMENT'; END IF; INSERT INTO leave_requests (organization_id, employee_id, start_date, end_date, leave_type, reason, status, submitted_at, version) VALUES (target_organization_id, employee.id, start_date, end_date, leave_type, NULLIF(btrim(reason), ''), 'submitted', now_at, 1) RETURNING * INTO request; INSERT INTO leave_request_events (organization_id, leave_request_id, request_version, action, actor_profile_id, actor_role, organization_timezone, prior_status, resulting_status) SELECT target_organization_id, request.id, 1, 'submitted', actor, membership.role::text, organization.timezone, NULL, 'submitted' FROM memberships membership JOIN organizations organization ON organization.id = target_organization_id WHERE membership.profile_id = actor AND membership.organization_id = target_organization_id; RETURN jsonb_build_object('id', request.id, 'status', request.status, 'version', request.version, 'submittedAt', request.submitted_at); EXCEPTION WHEN exclusion_violation THEN RAISE EXCEPTION 'TIME_OFF_OVERLAP'; END; $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION transition_leave_request(target_organization_id uuid, target_request_id uuid, expected_version integer, action text, decision_note text DEFAULT NULL, fallback_reason text DEFAULT NULL, retry_request_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$ DECLARE actor uuid; request leave_requests%ROWTYPE; actor_role text; next_status leave_status; now_at timestamptz := transaction_timestamp(); BEGIN actor := current_time_off_profile(target_organization_id); IF actor IS NULL THEN RAISE EXCEPTION 'TIME_OFF_FORBIDDEN'; END IF; SELECT request.* INTO request FROM leave_requests request WHERE request.id = target_request_id AND request.organization_id = target_organization_id FOR UPDATE; IF request.id IS NULL THEN RAISE EXCEPTION 'TIME_OFF_UNAVAILABLE'; END IF; SELECT membership.role::text INTO actor_role FROM memberships membership WHERE membership.organization_id = target_organization_id AND membership.profile_id = actor AND membership.status = 'active'; IF action = 'cancel' THEN next_status := 'cancelled'; ELSIF action = 'approve' THEN next_status := 'approved'; ELSE next_status := 'declined'; END IF; IF request.version <> expected_version THEN RAISE EXCEPTION 'TIME_OFF_STALE_VERSION'; END IF; IF request.status <> 'submitted' THEN RAISE EXCEPTION 'TIME_OFF_INVALID_STATE'; END IF; IF action = 'cancel' AND request.employee_id <> (SELECT id FROM employees WHERE profile_id = actor AND organization_id = target_organization_id) THEN RAISE EXCEPTION 'TIME_OFF_FORBIDDEN'; END IF; IF action <> 'cancel' AND actor_role NOT IN ('manager', 'administrator') THEN RAISE EXCEPTION 'TIME_OFF_FORBIDDEN'; END IF; IF action = 'decline' AND char_length(btrim(decision_note)) NOT BETWEEN 1 AND 500 THEN RAISE EXCEPTION 'TIME_OFF_INVALID_NOTE'; END IF; UPDATE leave_requests SET status = next_status, version = version + 1, reviewer_profile_id = CASE WHEN action <> 'cancel' THEN actor ELSE reviewer_profile_id END, decision_at = CASE WHEN action <> 'cancel' THEN now_at ELSE decision_at END, cancelled_at = CASE WHEN action = 'cancel' THEN now_at ELSE cancelled_at END, updated_at = now_at WHERE id = request.id; INSERT INTO leave_request_events (organization_id, leave_request_id, request_version, action, actor_profile_id, actor_role, organization_timezone, was_late, prior_status, resulting_status, decision_note, fallback_reason) SELECT target_organization_id, request.id, expected_version + 1, action::leave_event_action, actor, actor_role, organization.timezone, ((now_at AT TIME ZONE organization.timezone)::date > request.start_date), request.status, next_status, NULLIF(btrim(decision_note), ''), NULLIF(btrim(fallback_reason), '') FROM organizations organization WHERE organization.id = target_organization_id; RETURN jsonb_build_object('id', request.id, 'status', next_status, 'version', expected_version + 1, 'eventTime', now_at); END; $$;--> statement-breakpoint
REVOKE ALL ON FUNCTION current_time_off_profile(uuid), submit_leave_request(uuid, date, date, leave_type, text, uuid), transition_leave_request(uuid, uuid, integer, text, text, text, uuid) FROM PUBLIC, anon;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION submit_leave_request(uuid, date, date, leave_type, text, uuid), transition_leave_request(uuid, uuid, integer, text, text, text, uuid) TO authenticated;--> statement-breakpoint
CREATE OR REPLACE FUNCTION cancel_leave_request(target_organization_id uuid, target_request_id uuid, expected_version integer, retry_request_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$ SELECT transition_leave_request(target_organization_id, target_request_id, expected_version, 'cancel', NULL, NULL, retry_request_id) $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION approve_leave_request(target_organization_id uuid, target_request_id uuid, expected_version integer, fallback_reason text, retry_request_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$ SELECT transition_leave_request(target_organization_id, target_request_id, expected_version, 'approve', NULL, fallback_reason, retry_request_id) $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION decline_leave_request(target_organization_id uuid, target_request_id uuid, expected_version integer, decision_note text, fallback_reason text, retry_request_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$ SELECT transition_leave_request(target_organization_id, target_request_id, expected_version, 'decline', decision_note, fallback_reason, retry_request_id) $$;--> statement-breakpoint
CREATE OR REPLACE FUNCTION get_leave_request_detail(target_organization_id uuid, target_request_id uuid) RETURNS SETOF jsonb LANGUAGE sql SECURITY INVOKER SET search_path = public AS $$ SELECT jsonb_build_object('request', to_jsonb(request), 'events', COALESCE((SELECT jsonb_agg(to_jsonb(event) ORDER BY event.occurred_at, event.id) FROM leave_request_events event WHERE event.leave_request_id = request.id), '[]'::jsonb)) FROM leave_requests request WHERE request.id = target_request_id AND request.organization_id = target_organization_id AND request.status <> 'draft' $$;--> statement-breakpoint
