CREATE EXTENSION IF NOT EXISTS btree_gist;--> statement-breakpoint
ALTER TABLE leave_requests ADD CONSTRAINT leave_requests_active_overlap EXCLUDE USING gist (employee_id WITH =, daterange(start_date, end_date, '[]') WITH &&) WHERE (status IN ('submitted', 'approved'));--> statement-breakpoint
CREATE OR REPLACE FUNCTION active_time_off_member(target_organization_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM profiles profile JOIN memberships membership ON membership.profile_id = profile.id JOIN organizations organization ON organization.id = membership.organization_id WHERE profile.auth_user_id = auth.uid() AND profile.status = 'active' AND membership.organization_id = target_organization_id AND membership.status = 'active' AND organization.status = 'active') $$;--> statement-breakpoint
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE leave_request_events ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY time_off_authorized_requests ON leave_requests FOR SELECT USING (active_time_off_member(organization_id) AND EXISTS (SELECT 1 FROM profiles profile JOIN memberships membership ON membership.profile_id = profile.id LEFT JOIN employees actor ON actor.profile_id = profile.id AND actor.organization_id = leave_requests.organization_id JOIN employees target ON target.id = leave_requests.employee_id WHERE profile.auth_user_id = auth.uid() AND membership.organization_id = leave_requests.organization_id AND membership.status = 'active' AND (target.profile_id = profile.id OR target.manager_id = actor.id OR membership.role = 'administrator')));--> statement-breakpoint
CREATE POLICY time_off_authorized_events ON leave_request_events FOR SELECT USING (leave_request_id IN (SELECT id FROM leave_requests));--> statement-breakpoint
REVOKE ALL ON FUNCTION active_time_off_member(uuid) FROM PUBLIC, anon;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION active_time_off_member(uuid) TO authenticated;--> statement-breakpoint
