import Link from "next/link";
import { ActivityIcon, GaugeIcon, ListChecksIcon, ShieldAlertIcon, TimerResetIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { formatInstant } from "@/lib/hr-format";
import { cn } from "@/lib/utils";
import { getOperationsSummary } from "@/product-operations/queries";
import { ProductOperationsError } from "@/product-operations/errors";
import { FailureCard, EmptyFailures, HealthBadge, MetricCard, OperationsGroupUnavailable, OperationsPartialNotice, QueueCard, TrendText, WindowNav } from "./components/operations-ui";

export const metadata = { title: "Operations | HR Pulse" };

export default async function OperationsPage({ searchParams }) {
  const params = await searchParams;
  const selectedWindow = params?.window ?? "30d";
  let summary;
  let validationError = null;
  try { summary = await getOperationsSummary(selectedWindow); } catch (error) {
    if (!(error instanceof ProductOperationsError)) throw error;
    validationError = error.message;
  }
  if (!summary) return <div className="flex flex-col gap-8"><header><p className="text-sm font-medium text-muted-foreground">Product operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Operations are waiting for a valid window</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-foreground">Choose Today, Last 7 days, or Last 30 days to read the selected organization safely.</p></header><div role="alert" className="rounded-xl border border-destructive/50 bg-destructive/10 p-5 text-destructive">{validationError}</div><WindowNav selected="30d" /></div>;
  const activeMilestones = summary.adoption.state === "available" ? summary.adoption.total : null;
  const successCount = summary.workflowHealth.state === "available" ? summary.workflowHealth.areas.reduce((total, area) => total + area.success, 0) : null;
  const latencyRows = summary.latency.state === "available" ? summary.latency.rows : [];
  const averageLatency = latencyRows.length ? Math.round(latencyRows.reduce((total, row) => total + row.averageMs, 0) / latencyRows.length) : null;
  return <div className="flex flex-col gap-8">
    <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-muted-foreground">Product operations</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">See the pulse behind the work</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted-foreground">A calm, organization-scoped view of adoption, workflow health, payroll queue state, and bounded failures.</p></div><div className="flex flex-wrap gap-2"><Link className={cn(buttonVariants({ variant: "outline", size: "comfortable" }))} href="/operations/audit">Audit history<ListChecksIcon data-icon="inline-end" /></Link><WindowNav selected={selectedWindow} /></div></header>
    <div className="rounded-xl border border-border bg-accent/40 p-4 text-sm"><span className="font-medium">{selectedWindow === "today" ? "Today" : selectedWindow === "7d" ? "Last 7 days" : "Last 30 days"}</span><span className="ml-2 text-muted-foreground">All times use {summary.timezone}. Counts are aggregate for the selected workspace.</span></div>
    {summary.partial ? <OperationsPartialNotice /> : null}
    <section aria-labelledby="signal-title"><div className="mb-4"><h2 className="text-xl font-semibold" id="signal-title">Signal at a glance</h2><p className="mt-1 text-sm text-muted-foreground">Durable product milestones and workflow outcomes.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard description="Server milestones recorded in this window." icon={ActivityIcon} label="Milestones" unavailable={summary.adoption.state !== "available"} value={activeMilestones ?? "Unavailable"} /><MetricCard description="Successful workflow outcomes in this window." icon={GaugeIcon} label="Successful outcomes" unavailable={summary.workflowHealth.state !== "available"} value={successCount ?? "Unavailable"} /><MetricCard description="Average of available event latency groups." icon={TimerResetIcon} label="Average latency" unavailable={summary.latency.state !== "available"} value={averageLatency === null ? "No samples" : `${averageLatency} ms`} /><MetricCard description="Grouped failures last seen in this window." icon={ShieldAlertIcon} label="Failure groups" unavailable={summary.failures.state !== "available"} value={summary.failures.state === "available" ? summary.failures.rows.length : "Unavailable"} /></div></section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(0,0.85fr)]">
      <section aria-labelledby="adoption-title"><Card><CardHeader><CardTitle id="adoption-title">Adoption milestones</CardTitle><CardDescription>Fixed server events, with the previous matching window for context.</CardDescription><CardAction><Badge variant="information">Aggregate</Badge></CardAction></CardHeader><CardContent>{summary.adoption.state === "unavailable" ? <OperationsGroupUnavailable title="Adoption milestones" /> : <div className="grid gap-3 sm:grid-cols-2">{summary.adoption.milestones.map((milestone) => <div className="flex items-center justify-between gap-3 rounded-lg border border-border bg-muted/30 p-3" key={milestone.eventName}><div className="min-w-0"><p className="truncate text-sm font-medium">{milestone.label}</p><p className="truncate text-xs text-muted-foreground">{milestone.eventName}</p></div><div className="shrink-0 text-right"><p className="font-mono font-semibold tabular-nums">{milestone.count}</p><p className="text-xs text-muted-foreground">prior {milestone.priorCount}</p><TrendText value={milestone.trend} /></div></div>)}</div>}</CardContent></Card></section>
      <section aria-labelledby="queue-title"><h2 className="sr-only" id="queue-title">Payroll queue</h2><QueueCard queue={summary.queue} /></section>
    </div>
    <div className="grid gap-6 xl:grid-cols-2"><section aria-labelledby="health-title"><Card><CardHeader><CardTitle id="health-title">Workflow health</CardTitle><CardDescription>Success and error outcomes by workflow area.</CardDescription></CardHeader><CardContent>{summary.workflowHealth.state === "unavailable" ? <OperationsGroupUnavailable title="Workflow health" /> : <div className="flex flex-col gap-3">{summary.workflowHealth.areas.map((area) => <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3 last:border-0 last:pb-0" key={area.workflowArea}><p className="font-medium capitalize">{area.workflowArea.replaceAll("_", " ")}</p><div className="flex flex-wrap gap-2"><HealthBadge result="success" /><span className="font-mono text-sm tabular-nums">{area.success}</span>{area.expectedError ? <><HealthBadge result="expected_error" /><span className="font-mono text-sm tabular-nums">{area.expectedError}</span></> : null}{area.unexpectedError ? <><HealthBadge result="unexpected_error" /><span className="font-mono text-sm tabular-nums">{area.unexpectedError}</span></> : null}</div></div>)}</div>}</CardContent></Card></section><section aria-labelledby="latency-title"><Card><CardHeader><CardTitle id="latency-title">Latency groups</CardTitle><CardDescription>Only trusted server durations with available samples are shown.</CardDescription></CardHeader><CardContent>{summary.latency.state === "unavailable" ? <OperationsGroupUnavailable title="Latency groups" /> : latencyRows.length === 0 ? <p className="text-sm text-muted-foreground">No duration samples were recorded in this window.</p> : <div className="flex flex-col gap-3">{latencyRows.map((row) => <div className="grid gap-1 border-b border-border pb-3 last:border-0 last:pb-0 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center" key={row.eventName}><div><p className="font-medium">{row.label}</p><p className="text-xs text-muted-foreground">{row.sampleCount} samples</p></div><p className="font-mono text-sm tabular-nums">p50 {row.p50Ms} ms · p95 {row.p95Ms} ms</p></div>)}</div>}</CardContent></Card></section></div>
    <section aria-labelledby="failure-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-xl font-semibold" id="failure-title">Failure visibility</h2><p className="mt-1 text-sm text-muted-foreground">Safe grouped summaries; technical detail remains in protected Sentry.</p></div><Link className={cn(buttonVariants({ variant: "outline" }))} href="/operations/audit?result=unexpected_error">Unexpected audit results</Link></div>{summary.failures.state === "unavailable" ? <OperationsGroupUnavailable title="Failure visibility" /> : summary.failures.rows.length === 0 ? <EmptyFailures /> : <div className="grid gap-4 lg:grid-cols-2">{summary.failures.rows.map((failure) => <FailureCard failure={failure} key={failure.id} timezone={summary.timezone} />)}</div>}</section>
  </div>;
}
